server:
  port: 8086

spring:
  webflux:
    basePath: /banking-api

configType: "inMemory"

banking-api:
  initialCustomers:
    - id: 1
      name: John
      surname: Doe
    - id: 2
      name: Jane
      surname: Doe
    - id: 3
      name: Alice
      surname: Smith
    - id: 4
      name: Bob
      surname: Smith
